#!/bin/bash

source /usr/bin/ceph_internal_common_mon

if [ -z "$MON_ID" ] ; then
    echo "ERROR: MON_ID must be specified"
    exit 1
fi

start_mon $MON_ID
if [ $? -ne 0 ] ; then
    echo "ERROR: start_mon failed"
fi
